"""Standard-library audit, separate enumeration and arithmetic; no solver imports."""
from pathlib import Path
from collections import Counter,defaultdict
import json,hashlib,time,itertools
OUT=Path(__file__).resolve().parent
ROOT=OUT.parents[3]

def read(name):return json.loads((OUT/name).read_text())
def put(name,data):(OUT/name).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
def independent_domain(wall):
    result={}
    # Independent finite scan; power-square intersection is tested by cells.
    coverage={(x,y) for x in range(12) for y in range(12)}
    pole={(5,5),(5,6),(6,5),(6,6)}
    for x,y,w,h in itertools.product(range(-6,13),range(-6,13),range(3,7),range(3,7)):
        if (w,h) not in ((3,3),(5,5),(6,4),(4,6)):continue
        body={(x+i,y+j) for i in range(w) for j in range(h)}
        if not body&coverage or body&pole or (wall and any(a>6 for a,b in body)):continue
        axes=(0,1) if w==h else (1,) if w==6 else (0,)
        kind='s' if w==h==3 else 'm' if w==h==5 else 'l'
        for axis in axes:
            delta=(-1,0) if axis==0 else (0,-1)
            # Extract the two sides from the rectangle's cell boundary.
            lower=[(a+delta[0],b+delta[1]) for a,b in sorted(body) if (a+delta[0],b+delta[1]) not in body]
            upper=[(a-delta[0],b-delta[1]) for a,b in sorted(body) if (a-delta[0],b-delta[1]) not in body]
            sides=[[c for c in ps if c not in pole and (not wall or c[0]<=6)] for ps in (lower,upper)]
            if not all(sides):continue
            result[(kind,x,y,w,h,axis)]={'body':body,'ports':sides}
    return result

def check_model(wall):
    data=read('final_wall_model_a.json' if wall else 'final_general_model_a.json')
    expected=independent_domain(wall);objects=data['objects'];mapping={}
    for i,z in enumerate(objects):
        key=(z['kind'],*z['r'],z['axis']);assert key in expected and key not in mapping;mapping[key]=i
        assert set(map(tuple,z['body']))==expected[key]['body']
        assert [set(map(tuple,ps)) for ps in z['ports']]==[set(ps) for ps in expected[key]['ports']]
    assert set(mapping)==set(expected)
    inc=defaultdict(Counter)
    for key,i in mapping.items():
        for c in expected[key]['body']:inc[c][i]=1
    by_label={tuple(r['label']):r for r in data['rows']};labels=set()
    for c,co in inc.items():
        lab=('cell',*c);r=by_label[lab];assert dict(r['terms'])==co and r['rhs']==1;labels.add(lab)
    for key,i in mapping.items():
        for k,ps in enumerate(expected[key]['ports']):
            co=Counter({i:1})
            for c in ps:co.update(inc[c])
            lab=('port',i,k);r=by_label[lab]
            assert dict(r['terms'])==co and r['rhs']==len(ps);labels.add(lab)
    lab=('official_count',);r=by_label[lab]
    assert r['rhs']==(14 if wall else 23) and dict(r['terms'])=={i:1 for i in range(len(objects))};labels.add(lab)
    assert labels==set(by_label) and len(labels)==len(data['rows'])
    assert data['coefficients']==[2 if z['kind']=='s' else 3 for z in objects]
    # Encoding B was generated by another independent program and anchor order.
    b=read('domains_b.json')[str(wall)]
    bkeys={(z['kind'],*z['r'],z['axis']) for z in b}
    assert bkeys==set(expected)
    for z in b:
        e=expected[(z['kind'],*z['r'],z['axis'])]
        assert set(map(tuple,z['body']))==e['body']
        assert [set(map(tuple,ps)) for ps in z['ports']]==[set(ps) for ps in e['ports']]
    return dict(wall=wall,objects=len(objects),rows=len(data['rows']),independent_domain_equal=True,independent_rows_equal=True)

def witness(filename,wall,score):
    data=read(filename);domain=independent_domain(wall);selected=data['chosen'];occupied=set();keys=set()
    for z in selected:
        key=(z['kind'],*z['r'],z['axis']);assert key in domain and key not in keys
        assert occupied.isdisjoint(domain[key]['body']);occupied.update(domain[key]['body']);keys.add(key)
    for key in keys:
        assert all(set(ps)-occupied for ps in domain[key]['ports'])
    counts=Counter(z['kind'] for z in selected);actual=2*counts['s']+3*(counts['m']+counts['l'])
    assert actual==score and len(selected)<=(14 if wall else 23)
    return dict(file=filename,score=actual,counts=dict(counts),objects=len(keys),passes=True,
                scope='local geometric relaxation only; no production routing or periodic state constructed')

def tables():
    table={}
    for p in range(11):
        for j in range(min(1,p)+1):
            for b in range(87):
                ub=min(23*p-9*j,(54*p-25*j-b)//2)
                if ub>=b:table[p,j,b]=ub
    # Encoding 1: max-plus convolution of the local certified tables.
    dp={(0,0,0):0}
    for part in range(3):
        nextdp={}
        for (p,j,b),n in dp.items():
            for (q,k,c),v in table.items():
                key=p+q,j+k,b+c
                if key[0]>10 or key[1]>1 or key[2]>86:continue
                score=n+v
                if score>nextdp.get(key,-1):nextdp[key]=score
        dp=nextdp
    first=dp[10,1,86]
    # Encoding 2: direct enumeration of all resource triples, without the DP.
    second=-1;argmax=None;checked=0
    for p0 in range(11):
        for p1 in range(11-p0):
            pp=(p0,p1,10-p0-p1)
            for edge in range(3):
                jj=tuple(int(i==edge) for i in range(3))
                if not pp[edge]:continue
                for b0 in range(87):
                    for b1 in range(87-b0):
                        bb=(b0,b1,86-b0-b1);nn=[]
                        for p,j,b in zip(pp,jj,bb):
                            # Recompute directly instead of looking up table.
                            a=(54*p-25*j-b)//2;c=23*p-9*j;value=min(a,c)
                            if value<b:break
                            nn.append(value)
                        if len(nn)!=3:continue
                        checked+=1;value=sum(nn)
                        if value>second:second=value;argmax=dict(p=pp,j=jj,medium_plus_large=bb,upper=nn)
    assert first==second==214
    out=dict(weighted_single_pole=[54,29],weighted_total=9*54+29,
             required_sizes=dict(small=68+51+6+6,medium=32+16,large=32+3+3),
             required_weighted=2*(68+51+6+6)+3*(32+16+32+3+3),
             DP_upper=first,direct_enumeration_upper=second,direct_cases=checked,table_optimum_witness=argmax,
             table=[dict(p=p,j=j,medium_plus_large=b,upper=n) for (p,j,b),n in sorted(table.items())])
    assert out['weighted_total']==515 and out['required_weighted']==520
    put('fragment_tables.json',out)
    return {k:v for k,v in out.items() if k!='table'}

def main():
    start=time.monotonic();result={}
    result['models']=[check_model(False),check_model(True)]
    result['witnesses']=[witness('final_general_a_witness.json',False,54),witness('final_wall_a_opt.json',True,29)]
    result['tables']=tables()
    next_by_pairs=max(w*h for w in range(6,69) for h in range(6,69) if w*h<1113)
    next_by_divisors=next(a for a in range(1112,35,-1) if any(a%d==0 and 6<=a//d<=68 for d in range(6,69)))
    assert next_by_pairs==next_by_divisors==1110
    result['next_integer_rectangle_area']=dict(by_pairs=next_by_pairs,by_divisors=next_by_divisors)
    result['formal_input_hashes']={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in ['《明日方舟：终末地》游戏规则.txt','求解任务.txt','求解约束.txt']}
    result['seconds']=time.monotonic()-start;put('final_independent_audit.json',result);print(result,flush=True)
if __name__=='__main__':main()
